# Generated by Django 4.2.3 on 2023-07-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('support_request', '0001_initial'), ('support_request', '0002_alter_supportrequest_contact_and_more'), ('support_request', '0003_alter_supportrequest_state')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='добавлено')),
                ('number', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='номер')),
                ('short_description', models.CharField(max_length=255, verbose_name='краткое описание')),
                ('author', models.CharField(max_length=255, verbose_name='заявитель')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('proc', 'В работе'), ('rjct', 'Отклонена'), ('clsd', 'Закрыта')], default='new', max_length=4, verbose_name='статус')),
                ('decision', models.CharField(blank=True, max_length=255, null=True, verbose_name='решение')),
                ('state', models.CharField(default='Состояние 0', max_length=255, verbose_name='состояние')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='крайний срок')),
                ('closed', models.BooleanField(default=False, verbose_name='закрыто')),
                ('description', models.TextField(verbose_name='подробное описание')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='контактное лицо')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
    ]
